# Generated by Django 4.1.7 on 2023-03-10 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_num', models.CharField(db_column='flight_num', max_length=256)),
                ('origin_country', models.CharField(db_column='origin_country', max_length=50)),
                ('origin_city', models.CharField(db_column='origin_city', max_length=50)),
                ('origin_code', models.CharField(db_column='origin_code', max_length=50)),
                ('destination_country', models.CharField(db_column='destination_country', max_length=50)),
                ('destination_city', models.CharField(db_column='destination_city', max_length=50)),
                ('destination_code', models.CharField(db_column='destination_code', max_length=50)),
                ('origin_dt', models.BigIntegerField(db_column='origin_dt')),
                ('destination_dt', models.BigIntegerField(db_column='destination_dt')),
                ('total_seats', models.SmallIntegerField(db_column='total_seats')),
                ('seats_left', models.SmallIntegerField(db_column='seats_left')),
                ('is_cancelled', models.BooleanField(db_column='is_cancelled')),
                ('price', models.SmallIntegerField(db_column='price')),
            ],
            options={
                'db_table': 'flights',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.SmallIntegerField(db_column='number_of_seats')),
                ('order_date', models.DateTimeField(db_column='order_date')),
                ('total_price', models.SmallIntegerField(db_column='total_price')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.flight')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
